"""
Mock HRIS API — simulates a Workday-style HR System.

Serves employee and event data generated by synthetic_generator.py.
Called hourly by Airflow hris_ingestion_dag for delta sync.

Endpoints:
  GET  /hris/employees              Paginated employee list
  GET  /hris/employees/{id}         Single employee profile
  GET  /hris/events?since={ts}      Delta sync: events since ISO timestamp
  POST /hris/employees/{id}/update  Simulate HR record update
  GET  /health                      Liveness check
"""

import json
import os
from datetime import date, datetime, timezone
from typing import Optional

import psycopg2
import psycopg2.extras
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse

from schemas import (
    EmployeeListOut,
    EmployeeOut,
    EmployeeUpdateIn,
    EmployeeUpdateOut,
    EventsOut,
    HREventOut,
)

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://talentlens:talentlens@localhost:5432/talentlens")

app = FastAPI(
    title="TalentLens Mock HRIS API",
    description="Simulates a Workday HR System for TalentLens ingestion pipeline.",
    version="1.0.0",
)


def get_conn():
    return psycopg2.connect(DATABASE_URL, cursor_factory=psycopg2.extras.RealDictCursor)


# ─────────────────────────────────────────────────────────────────────────────
# Health
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute("SELECT 1")
        conn.close()
        return {"status": "ok", "db": "connected"}
    except Exception as e:
        return JSONResponse(status_code=503, content={"status": "error", "detail": str(e)})


# ─────────────────────────────────────────────────────────────────────────────
# Employees
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/hris/employees", response_model=EmployeeListOut)
def list_employees(
    page: int = Query(1, ge=1),
    page_size: int = Query(100, ge=1, le=1000),
    department: Optional[str] = None,
    is_active: Optional[bool] = None,
):
    offset = (page - 1) * page_size
    filters = []
    params: list = []

    if department:
        filters.append("department = %s")
        params.append(department)
    if is_active is not None:
        filters.append("is_active = %s")
        params.append(is_active)

    where = ("WHERE " + " AND ".join(filters)) if filters else ""

    conn = get_conn()
    cur = conn.cursor()

    cur.execute(f"SELECT COUNT(*) AS total FROM raw.hris_employee_snapshot {where}", params)
    total = cur.fetchone()["total"]

    cur.execute(
        f"SELECT * FROM raw.hris_employee_snapshot {where} ORDER BY hire_date DESC LIMIT %s OFFSET %s",
        params + [page_size, offset],
    )
    rows = cur.fetchall()
    conn.close()

    employees = [EmployeeOut(**dict(r)) for r in rows]
    return EmployeeListOut(
        data=employees,
        total=total,
        page=page,
        page_size=page_size,
        has_next=(offset + page_size) < total,
    )


@app.get("/hris/employees/{employee_id}", response_model=EmployeeOut)
def get_employee(employee_id: str):
    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        "SELECT * FROM raw.hris_employee_snapshot WHERE employee_id = %s",
        (employee_id,),
    )
    row = cur.fetchone()
    conn.close()

    if not row:
        raise HTTPException(status_code=404, detail=f"Employee {employee_id} not found")
    return EmployeeOut(**dict(row))


@app.post("/hris/employees/{employee_id}/update", response_model=EmployeeUpdateOut)
def update_employee(employee_id: str, update: EmployeeUpdateIn):
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        "SELECT employee_id FROM raw.hris_employee_snapshot WHERE employee_id = %s",
        (employee_id,),
    )
    if not cur.fetchone():
        conn.close()
        raise HTTPException(status_code=404, detail=f"Employee {employee_id} not found")

    updates = update.model_dump(exclude_none=True)
    if not updates:
        conn.close()
        raise HTTPException(status_code=400, detail="No fields to update")

    set_clause = ", ".join(f"{k} = %s" for k in updates)
    values = list(updates.values()) + [employee_id]

    cur.execute(
        f"UPDATE raw.hris_employee_snapshot SET {set_clause} WHERE employee_id = %s",
        values,
    )
    conn.commit()
    conn.close()

    return EmployeeUpdateOut(
        employee_id=employee_id,
        updated_fields=list(updates.keys()),
        updated_at=datetime.now(timezone.utc),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Events (delta sync)
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/hris/events", response_model=EventsOut)
def get_events(
    since: Optional[str] = Query(None, description="ISO 8601 datetime; returns events after this timestamp"),
    event_type: Optional[str] = None,
    department: Optional[str] = None,
    limit: int = Query(10_000, ge=1, le=50_000),
):
    filters = []
    params: list = []

    if since:
        try:
            since_dt = datetime.fromisoformat(since.replace("Z", "+00:00"))
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid 'since' format. Use ISO 8601.")
        filters.append("_ingested_at > %s")
        params.append(since_dt)

    if event_type:
        filters.append("event_type = %s")
        params.append(event_type)

    if department:
        filters.append("department = %s")
        params.append(department)

    where = ("WHERE " + " AND ".join(filters)) if filters else ""

    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        f"""SELECT event_id, employee_id, event_type, event_date, department, payload
            FROM raw.employee_events {where}
            ORDER BY event_date ASC
            LIMIT %s""",
        params + [limit],
    )
    rows = cur.fetchall()

    cur.execute(f"SELECT COUNT(*) AS total FROM raw.employee_events {where}", params)
    total = cur.fetchone()["total"]
    conn.close()

    events = [
        HREventOut(
            event_id=str(r["event_id"]),
            employee_id=str(r["employee_id"]),
            event_type=r["event_type"],
            event_date=r["event_date"],
            department=r["department"],
            payload=json.loads(r["payload"]) if r["payload"] else None,
        )
        for r in rows
    ]

    return EventsOut(data=events, total=total, since=since)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8001, reload=True)
